version: '3.8'

services:

  db:
    image: postgres:14
    container_name: postgres_db
    env_file:
      - ./back-end/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Exposes Postgres on port 5432

  backend:
    build:
      context: ./
      dockerfile: ./containers/Dockerfile.server
    container_name: django_api
    env_file:
      - ./back-end/.env  # Points to your Django .env file
    volumes:
      - ./back-end:/app  # Mounts your local Django project to the container
    ports:
      - "8000:8000"      # Exposes the Django dev server on port 8000
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  pgdata: