version: '3.8'

services:

  db:
    image: postgres:14
    container_name: postgres_db
    env_file:
      - ./back-end/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"

  backend:
    build:
      context: ./
      dockerfile: ./containers/Dockerfile.server
    container_name: django_api
    env_file:
      - ./back-end/.env
    volumes:
      - ./back-end:/app
    # ports:
    #   - "8000:8000"
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./containers/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
